[package]
name = "mol"
version = "0.1.0"
authors = ["Moritz Kneilmann <moritz.kneilmann@gmx.de>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
rustyline = "5.0.0"
clap = "2.33.0"
colored = "1.9.0"
pretty_assertions = "0.6.1"

[build-dependencies]
peg = "0.5.7"
